# Generated by Django 2.2.8 on 2020-01-14 11:52

from django.conf import settings
from django.contrib.gis.geos import MultiPolygon
from django.db import migrations


def _set_domains(apps, schema_editor):
    parking_model = apps.get_model('parkings', 'Parking')
    parking_area_model = apps.get_model('parkings', 'ParkingArea')
    payment_zone_model = apps.get_model('parkings', 'PaymentZone')
    parking_terminal_model = apps.get_model('parkings', 'ParkingTerminal')
    permit_model = apps.get_model('parkings', 'Permit')
    permit_area_model = apps.get_model('parkings', 'PermitArea')

    parkings = parking_model.objects.filter(domain=None)
    if parkings.exists():
        parkings.update(domain=_get_or_create_enforcement_domain(apps))

    parking_areas = parking_area_model.objects.filter(domain=None)
    if parking_areas.exists():
        parking_areas.update(domain=_get_or_create_enforcement_domain(apps))

    parking_terminals = parking_terminal_model.objects.filter(domain=None)
    if parking_terminals.exists():
        parking_terminals.update(domain=_get_or_create_enforcement_domain(apps))

    permits = permit_model.objects.filter(domain=None)
    if permits.exists():
        permits.update(domain=_get_or_create_enforcement_domain(apps))

    permit_areas = permit_area_model.objects.filter(domain=None)
    if permit_areas.exists():
        permit_areas.update(domain=_get_or_create_enforcement_domain(apps))

    payment_zones = payment_zone_model.objects.filter(domain=None)
    if payment_zones.exists():
        payment_zones.update(domain=_get_or_create_enforcement_domain(apps))

    for payment_zone in payment_zone_model.objects.filter(code=None):
        payment_zone.code = str(payment_zone.number)
        payment_zone.save(update_fields=["code"])


def _get_or_create_enforcement_domain(apps):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    payment_zone_model = apps.get_model('parkings', 'PaymentZone')
    enforcement_domain_model = apps.get_model('parkings', 'EnforcementDomain')
    domain_geom = None
    for payment_zone in payment_zone_model.objects.all():
        if domain_geom is None:
            domain_geom = payment_zone.geom
        else:
            domain_geom |= payment_zone.geom

    name, code = getattr(settings, "DEFAULT_ENFORCEMENT_DOMAIN")
    enforcement_domain, created = enforcement_domain_model.objects.get_or_create(
        code=code,
        defaults={
            "name": name,
            "geom": MultiPolygon(domain_geom),
        }
    )
    if created:
        for user in user_model.objects.filter(is_staff=True):
            enforcement_domain.enforcers.add(user)

    return enforcement_domain


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0029_enforcement_domain'),
    ]

    operations = [
        migrations.RunPython(_set_domains, migrations.RunPython.noop),
    ]
